### PR TITLE
Update pyfancy.py

### PR DESCRIPTION
**Pull request by joker314**
Testing now, please wait

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
OK

**Comment by TheMonsterFromTheDeep** [comment]
Okay guise dont merge it until we know it works

**Comment by CosmicWebServices** [comment]
Yes sorry about that

**Comment by joker314** [comment]
Error, it thinks it wants me to typecast to string or something. Wrking on it now

**Comment by CosmicWebServices** [comment]
OK

**Comment by TheMonsterFromTheDeep** [comment]
I know how to fix it guise

**Comment by CosmicWebServices** [comment]
What is wrong with it?

**Comment by TheMonsterFromTheDeep** [comment]
Okay I fixed it

**Comment by CosmicWebServices** [comment]
Cool check out #11

**Comment by joker314** [comment]
No, I think I solved it, what?

**Comment by TheMonsterFromTheDeep** [comment]
I've already merged this :]

**Pull request merged**
