### PR TITLE
Parsing

### PR DESCRIPTION
**Pull request by TheMonsterFromTheDeep**
Because the parsing code is incomplete, I have moved it into a new branch. See [this pr](https://github.com/TheMonsterFromTheDeep/pyfancy/pull/5) for the original discussion.

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
Can we finish this

**Comment by TheMonsterFromTheDeep** [comment]
Maybe someday. ;)

Right now I'm at work though. :package:

**Comment by CosmicWebServices** [comment]
Yeah

**Comment by CosmicWebServices** [comment]
I merged it today because I just needed to but this will be added in a later version

**Comment by TheMonsterFromTheDeep** [comment]
Okay...

**Comment by joker314** [comment]
Closing due to conflicts, again :(

**Comment by CosmicWebServices** [comment]
@joker314 Wow I forgot about this

**Pull request closed without merging**
