### PR TITLE
Started to add stuff

### PR DESCRIPTION
**Pull request by joker314**
Trying to add formatted string support, and made a small tweak with my rainbow

### CODE REVIEW

**Comment by joker314** [comment]
Note: I would like to see what exception this gives when you run it

**Comment by joker314** [comment]
(So don't merge without testing)

Bump

**Comment by CosmicWebServices** [comment]
What does `run()` do?

**Comment by joker314** [comment]
`"red{text goes \{ here \}".run()`

It i just an initial attempt at it

**Comment by joker314** [comment]
No, `obj.run("red{some red text} normal text blue{some \{escaped\} blue text}")`

**Comment by CosmicWebServices** [comment]
Now I am confused I thought it was stackable functions not this or am I just not understanding

**Comment by joker314** [comment]
Yes, is is that. But I am giving the user the option of using this method instead, so they can stack on top of it and in front of it: `obj.red("Hi").blue("Yo").run("Me too bold{lazy} to use stackablez").get()`

**Comment by joker314** [comment]
That wuld produce some red text followed by some blue text then some bold text. ut it isn't finished, but I'm keeping the PR so that there are no duplicated

**Comment by CosmicWebServices** [comment]
That is nice!

**Comment by CosmicWebServices** [comment]
I should have made pyfancy a team project a long time ago I would have never thought of these ideas u guys have

**Comment by joker314** [comment]
Thx, I will now try and test it _fingers crossed_

**Comment by CosmicWebServices** [comment]
I will test it also later

**Comment by TheMonsterFromTheDeep** [comment]
I think the function name should be parse(), and it should be possible to chain it on like the rest of the statements.

Its string argument should be mandatory (as it seems it already is....) because there is no way to stack it on like the other styles.

**Comment by TheMonsterFromTheDeep** [comment]
So, if I understand right, the parsing still doesn't work correctly, right?

**Comment by CosmicWebServices** [comment]
Do not think so

**Comment by TheMonsterFromTheDeep** [comment]
I have moved this discussion to [this new pr](https://github.com/TheMonsterFromTheDeep/pyfancy/pull/6) so that we can all contribute to the parsing code.

**Pull request closed without merging**
