### PR TITLE
__init__

### PR DESCRIPTION
**Pull request by joker314**
To allow people to pass existing pyfancy objects or strings to initialize

Warning: Untested

### CODE REVIEW

**Comment by joker314** [comment]
Anybody got any opinions on this?

**Comment by CosmicWebServices** [comment]
Test it first

**Comment by joker314** [comment]
Ok, tested and fixed bugs

**Comment by CosmicWebServices** [comment]
@TheMonsterFromTheDeep should we merge?

**Comment by TheMonsterFromTheDeep** [comment]
Sure!

**Pull request merged**
