### PR TITLE
Get rid of boilerplate in methods

### PR DESCRIPTION
**Pull request by jeandrek**
Is this good?

### CODE REVIEW

**Comment by jeandrek** [comment]
Should `sgr` be a class method?

**Comment by TheMonsterFromTheDeep** [comment]
> Should sgr be a class method?

Probably? I haven't really done Python before so I don't know, but that's what I would do in Java/C++...

Also, what's sgr stand for (or whatever?)

**Comment by joker314** [comment]
Oh no! Conflicts D:

**Comment by joker314** [comment]
I think it should be added but with an alias of .custom() which is actually .sgr (to save memory)

**Comment by TheMonsterFromTheDeep** [comment]
So, I've butchered this pull request into [this new branch](https://github.com/TheMonsterFromTheDeep/pyfancy/tree/no-boilerplate) and I think I have some cool ways to make it even better...

EDIT: Actually, I have no idea what I'm talking about. But I think that this can be cleaned up a bit, maybe...

**Comment by CosmicWebServices** [comment]
Put `sgr(code)` into class pyfancy that may fix the conflicts

**Comment by CosmicWebServices** [comment]
This seems to reverse back to the old pyfancy just with new code... I do not see the benefit

**Comment by CosmicWebServices** [comment]
^^^ @TheMonsterFromTheDeep ^^^

**Comment by TheMonsterFromTheDeep** [comment]
It's really nice because we don't have to rewrite the same method every time.

I'm just trying to see how it could be made nicer...

**Comment by CosmicWebServices** [comment]
But this will make the whole stackable thing not work

**Comment by TheMonsterFromTheDeep** [comment]
No, it still works. It just calls a function that returns a function in order to generate the functions. It is basically functionally equivalent.

**Comment by CosmicWebServices** [comment]
Oh really? Sorry I misunderstood... We need to fix the conflicts first and update the code

**Comment by TheMonsterFromTheDeep** [comment]
I'm actually working on making this even cooler :]

**Comment by CosmicWebServices** [comment]
Cool

**Comment by jeandrek** [comment]
> Also, what's sgr stand for (or whatever?)

"Select Graphic Rendition". ANSI escape codes that start with `<ESC>[` and end with `m` are SGR codes.

**Comment by jeandrek** [comment]
Should this be closed in favor of #13?

**Comment by CosmicWebServices** [comment]
I guess so

**Comment by TheMonsterFromTheDeep** [comment]
@Jonathan50 Yeah I think I meant to do that :package:

**Pull request closed without merging**
