### PR TITLE
Added rainbow

### PR DESCRIPTION
**Pull request by joker314**
Well, at least I think I did

### CODE REVIEW

**Comment by joker314** [comment]
I didn't know you were working on it too. I'm sorry. I can close this if you like

**Comment by TheMonsterFromTheDeep** [comment]
I don't know - We can decide which one is better. :]

**Comment by joker314** [comment]
Paste your code here. I used an array of functions. I think @Jonathan50 made this one a bit conflicting with theirs. Merge his first, then I'll copy my rainbow code onto a PR to the merged version to stop coonflicts

**Comment by TheMonsterFromTheDeep** [comment]
^ My rainbow is in the repo right now. It looks like this:

``` python
# Rainbow text (cycles through different modifiers)
    def rainbow(self,string):
        i = 31 # ID of escape code; starts at 31 (red) and goes to 36 (cyan)
        for c in string: # Iterate through string
            self.out += "\033[" + str(i) + "m" + c
            i += 1 # Why u no have ++i? >:(
            if(i > 36): i = 31
        return self
```

**Comment by joker314** [comment]
That works! So does mine I guess. What are we goingg to do with Jonathan's conflict with the base branch?

**Comment by joker314** [comment]
Actually that doesn't work. Th rainbow isn't in order. Unless that is your intention?

**Comment by TheMonsterFromTheDeep** [comment]
Well, I wasn't actually looking for _real_ rainbows - that's why yours might be better. :package:

**Comment by joker314** [comment]
We could create two methods, rainbow(), and multi()

**Comment by joker314** [comment]
Ready to merge? And then we need to make this compatible with Jonathan50 _and_ we need to change your function name to "multi"

**Comment by TheMonsterFromTheDeep** [comment]
Okay

**Comment by TheMonsterFromTheDeep** [comment]
I'll go merge it

**Comment by joker314** [comment]
I implemented white-space checks. So now "Hi hello" would be Red, Orange, Space, Yellow etc. So there isn't a jump in colour when you have a whitespace/newline/etc.

**Comment by joker314** [comment]
Is it compatible with Jonathan50?

**Comment by TheMonsterFromTheDeep** [comment]
Okay - I'll go test them while merging it

**Comment by TheMonsterFromTheDeep** [comment]
What do you mean by is it compatible?

**Comment by joker314** [comment]
Didn't they change everything to use svg()

**Comment by TheMonsterFromTheDeep** [comment]
Yes, but we still have to figure out what we're going to do with that before merging it too

**Comment by joker314** [comment]
Ok. Merge when ready.

**Comment by TheMonsterFromTheDeep** [comment]
The darn thing just wasn't working when I tried to fix it locally so I'll have to clean it up here...

**Pull request merged**
