### PR TITLE
Update pyfancy.py

### PR DESCRIPTION
**Pull request by joker314**
They can't flow into each other, you can't close all your HTML tags at the end would be the analogy.

If I understand correctly?

### CODE REVIEW

**Comment by jeandrek** [comment]
Users should close everything with .raw(), I think. This breaks using multiple things, such as bold and red.

**Comment by joker314** [comment]
Yes, but what if you do .red().blue() and it would only close once.

**Comment by jeandrek** [comment]
`<ESC>[0m` **resets** everything. So `pyfancy().red().blue().raw('bar')` will print bar in default colors, because .raw() has resseted everything.

**Comment by joker314** [comment]
What happens if you nest .red().blue() what will the text within be? (I presume blue?)

**Comment by jeandrek** [comment]
The escape codes always just override the previous ones. I edited my comment.

**Comment by joker314** [comment]
You know what they say, learn something new about ANSI codes everyday

**Comment by TheMonsterFromTheDeep** [comment]
They are supposed to flow into each other. When you use .get(), it automatically closes them. I guess I should also make that clear in the README.

**Pull request closed without merging**
