### PR TITLE
No boilerplate

### PR DESCRIPTION
**Pull request by TheMonsterFromTheDeep**
This makes the code much more maintainable and nicer. It also allows us to directly reference color IDs to do things.

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
Is it tested?

**Comment by TheMonsterFromTheDeep** [comment]
To some extent, yes.

**Comment by CosmicWebServices** [comment]
When can we add this?

**Comment by CosmicWebServices** [comment]
Also can it be simplified any more than it is already?

**Comment by joker314** [comment]
Does this mean you have to type the style name in quotes to call, or does it work a normal?

**Comment by CosmicWebServices** [comment]
Works as normal

**Comment by CosmicWebServices** [comment]
When will we merge this?

**Comment by TheMonsterFromTheDeep** [comment]
I thought I already had...

**Comment by CosmicWebServices** [comment]
no

**Comment by CosmicWebServices** [comment]
I will merge when u give me the OK

**Comment by joker314** [comment]
Conflicts D: ?

**Comment by CosmicWebServices** [comment]
Sadly

**Comment by TheMonsterFromTheDeep** [comment]
Tada is merged

**Comment by jeandrek** [comment]
How?

**Comment by TheMonsterFromTheDeep** [comment]
I merged it? :P What do you mean "how?"

**Comment by jeandrek** [comment]
How did you merge it when there were conflicts?

**Comment by TheMonsterFromTheDeep** [comment]
I resolved the conflicts locally. :P

**Comment by jeandrek** [comment]
~~How?~~ Nvm, see https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**Comment by CosmicWebServices** [comment]
Cool

**Pull request merged**
