### PR TITLE
Update pyfancy.py

### PR DESCRIPTION
**Pull request by joker314**
Fixed rainbow bug

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
Nice is it tested?

**Comment by joker314** [comment]
I tested but found that I forgot to add a return value, but it doesn't throw anything! Give me a sec

**Comment by TheMonsterFromTheDeep** [comment]
Once its ready we can merge it :]

**Comment by joker314** [comment]
Testing final update

**Comment by CosmicWebServices** [comment]
Good Merging...

**Comment by TheMonsterFromTheDeep** [comment]
Do we know if it works?

**Comment by CosmicWebServices** [comment]
Yes

**Comment by joker314** [comment]
Error, can I create a new PR

**Comment by joker314** [comment]
If you've already merged

**Comment by TheMonsterFromTheDeep** [comment]
We can just revert this one

**Comment by CosmicWebServices** [comment]
OK I will revert it

**Comment by TheMonsterFromTheDeep** [comment]
Actually nevermind just make a new one

**Comment by TheMonsterFromTheDeep** [comment]
Or whatever :P

**Pull request merged**
